### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by CherbyMina** [HQAnime/AnimeGo-Re#43]
Hello! Can we have a feature where we can put any anime site link in the app? So that if gogo anime is not working we can use another sires' link to watch...

Or we can do that already in the app?

Because when i put animepahe sites' link it's not working...

Hope you notice hehe

**Comment by HenryQuan** [comment]
This app is only for Gogoanime.  I don't plan to support other sites.

**Comment by CherbyMina** [comment]
> This app is only for Gogoanime.  I don't plan to support other sites.

Okay
