### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by CherbyMina** [HQAnime/AnimeGo-Re#44]
Stuck in loading screen when cliking anime

**Comment by HenryQuan** [comment]
Does the website work for you?

**Comment by CherbyMina** [comment]
> Does the website work for you?

Yeah but I'm stuck in loading screen when i click one anime the website works fine tho.

**Comment by HenryQuan** [comment]
Does it happen to all anime? If the website loads, the app should also load.

**Comment by CherbyMina** [comment]
> Does it happen to all anime? If the website loads, the app should also load.

Stuck in loading screen when cliking an anime is fixed to me now thanks...

But the issue transfer when i click an anime episode to watch and it's stuck again 🤣...

**Comment by HenryQuan** [comment]
Emm, I see. This is a bit strange. It's working on my device. Can you try opening it on the website?

**Comment by CherbyMina** [comment]
> Emm, I see. This is a bit strange. It's working on my device. Can you try opening it on the website?

Site's working fine tho but inside the app it's really not...

**Comment by HenryQuan** [comment]
This does work on my device. How does did it take to load on the website. The app has a 8s timeout. Not sure if it hit the timeout.

**Comment by HenryQuan** [comment]
I may know the reason why. You are using a different website. Please change the website url to https://gogoanimes.to. The app won't work if you are using gogoanime.fi.

**Comment by HenryQuan** [comment]
No problem. Some other gogoanime sites may actually work but there are just too many of them. There are some minor differences so parsers won't work correctly. I can try a few more once I am focusing on this app again.
